import {
  Stethoscope,
  Plane,
  TrendingUp,
  Search,
  MousePointerClick,
  Megaphone,
  MessagesSquare,
  Users,
  Bot,
  Award,
  Palette,
  Shapes,
  MonitorSmartphone,
  PenTool,
  Clapperboard,
  ShoppingBag,
  CalendarHeart,
  Camera,
} from "lucide-react";

export const serviceIcons: Record<
  string,
  React.ComponentType<{ className?: string }>
> = {
  "saglik-reklamciligi": Stethoscope,
  "saglik-turizmi-pazarlamasi": Plane,
  "dijital-pazarlama-yonetimi": TrendingUp,
  seo: Search,
  "google-ads": MousePointerClick,
  "meta-reklamlari": Megaphone,
  "sosyal-medya-yonetimi": MessagesSquare,
  "influencer-marketing": Users,
  "yapay-zeka-destekli-pazarlama": Bot,
  "marka-yonetimi": Award,
  "kurumsal-kimlik": Palette,
  "grafik-tasarim": Shapes,
  "web-tasarim": MonitorSmartphone,
  "icerik-uretimi": PenTool,
  "gorsel-isitsel-produksiyon": Clapperboard,
  "urun-fotografciligi": ShoppingBag,
  "ozel-gun-cekimleri": CalendarHeart,
  "kurumsal-fotograf": Camera,
};
